from __future__ import annotations

from enum import Enum as PyEnum


class RecommendationType(str, PyEnum):
    PRACTICE_TOPIC = "PRACTICE_TOPIC"
    INCREASE_DIFFICULTY = "INCREASE_DIFFICULTY"
    REVIEW_FOUNDATION = "REVIEW_FOUNDATION"
    DEBUG_ERROR_PATTERN = "DEBUG_ERROR_PATTERN"
    IMPROVE_CONSISTENCY = "IMPROVE_CONSISTENCY"
    EXPAND_TOPIC_BREADTH = "EXPAND_TOPIC_BREADTH"
    OPTIMIZATION_PRACTICE = "OPTIMIZATION_PRACTICE"
    COMPLETE_MENTOR_TASK = "COMPLETE_MENTOR_TASK"


class RecommendationPriority(str, PyEnum):
    CRITICAL = "CRITICAL"
    HIGH = "HIGH"
    MEDIUM = "MEDIUM"
    LOW = "LOW"


MAX_ACTIVE_RECOMMENDATIONS = 5
RECOMMENDATION_DUPLICATE_WINDOW_DAYS = 7
RECOMMENDATION_MIN_PROBLEMS_PER_TOPIC = 3
RECOMMENDATION_WEAK_SOLVE_RATE_THRESHOLD = 0.5
RECOMMENDATION_LOW_DIFFICULTY_THRESHOLD = 0.65
